# Generated by Django 6.0.3 on 2026-04-01 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seeded', models.DateTimeField(blank=True, null=True)),
                ('total_funds', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Seed Status',
            },
        ),
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.IntegerField(db_index=True, unique=True)),
                ('scheme_name', models.CharField(max_length=500)),
                ('amc', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('fund_type', models.CharField(blank=True, max_length=100)),
                ('current_nav', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('nav_date', models.DateField(blank=True, null=True)),
                ('nav_last_updated', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheme_name'],
                'indexes': [models.Index(fields=['scheme_name'], name='funds_mutua_scheme__aee0fc_idx'), models.Index(fields=['amc'], name='funds_mutua_amc_25f82f_idx')],
            },
        ),
        migrations.CreateModel(
            name='NAVHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nav', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='funds.mutualfund')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['fund', 'date'], name='funds_navhi_fund_id_cc9312_idx')],
                'unique_together': {('fund', 'date')},
            },
        ),
    ]
