# Generated by Django 4.2.29 on 2026-04-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='aum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assets Under Management in crores', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='crisil_rating',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='direct',
            field=models.CharField(blank=True, help_text='Y/N for direct plan', max_length=1),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='expense_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='face_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='fund_category',
            field=models.CharField(blank=True, help_text='Detailed fund category from API', max_length=200),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='fund_manager',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='investment_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='isin',
            field=models.CharField(blank=True, db_index=True, help_text='ISIN Div Payout/IDCW', max_length=20),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='lump_available',
            field=models.CharField(blank=True, help_text='Y/N', max_length=1),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='maturity_type',
            field=models.CharField(blank=True, help_text='Open Ended/Close Ended', max_length=50),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='plan',
            field=models.CharField(blank=True, help_text='GROWTH/DIVIDEND etc', max_length=50),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='redemption_allowed',
            field=models.CharField(blank=True, help_text='Y/N', max_length=1),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='sip_available',
            field=models.CharField(blank=True, help_text='Y/N', max_length=1),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='start_date',
            field=models.DateField(blank=True, help_text='Scheme inception date', null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags from API'),
        ),
        migrations.AddIndex(
            model_name='mutualfund',
            index=models.Index(fields=['isin'], name='funds_mutua_isin_f280af_idx'),
        ),
    ]
