# Generated by Django 4.2.29 on 2026-04-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_mutualfund_aum_mutualfund_crisil_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfund',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
