# Generated by Django 4.2.29 on 2026-04-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_change_is_active_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='day_change',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Day change in NAV', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='day_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Day change percentage', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='family_id',
            field=models.IntegerField(blank=True, help_text='Fund family ID from mfdata.in', null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='morningstar_rating',
            field=models.IntegerField(blank=True, help_text='Morningstar rating (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='plan_type',
            field=models.CharField(blank=True, help_text='Direct/Regular plan type', max_length=20),
        ),
    ]
