# Generated by Django 4.2.29 on 2026-04-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_add_mfdata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='alpha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='analyst_rating',
            field=models.CharField(blank=True, help_text='Gold/Silver/Bronze/Neutral/Negative', max_length=50),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='downside_capture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='exit_load',
            field=models.CharField(blank=True, help_text='Exit load details', max_length=500),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='fund_manager_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='fund_manager_tenure',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Manager tenure in years', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='max_drawdown',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='min_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='min_sip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='pb_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='pe_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='r_squared',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='rank_1y',
            field=models.IntegerField(blank=True, help_text='Category rank for 1Y return', null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='rank_3y',
            field=models.IntegerField(blank=True, help_text='Category rank for 3Y return', null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='rank_5y',
            field=models.IntegerField(blank=True, help_text='Category rank for 5Y return', null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='return_1m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='return_1y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='return_3m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='return_3y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='return_5y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='return_6m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='return_since_inception',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='sharpe_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='sortino_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='std_deviation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='total_in_category',
            field=models.IntegerField(blank=True, help_text='Total funds in category', null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='treynor_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='upside_capture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
