# Generated by Django 6.0.3 on 2026-04-01 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('fund_manager_change', 'Fund Manager Change'), ('category_change', 'Fund Category Change'), ('objective_change', 'Fund Objective Change'), ('nav_update', 'NAV Update'), ('new_holding', 'New Holding Added'), ('holding_exit', 'Holding Fully Exited'), ('weight_change', 'Significant Weight Change'), ('sector_change', 'Sector Allocation Change'), ('system', 'System Alert'), ('factsheet_error', 'Factsheet Error')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.mutualfund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='alerts_aler_user_id_d01ece_idx')],
            },
        ),
    ]
