# Generated by Django 4.2.29 on 2026-04-13 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('fund_manager_change', 'Fund Manager Change'), ('category_change', 'Fund Category Change'), ('objective_change', 'Fund Objective Change'), ('nav_update', 'NAV Update'), ('new_holding', 'New Holding Added'), ('holding_exit', 'Holding Fully Exited'), ('weight_change', 'Significant Weight Change'), ('sector_change', 'Sector Allocation Change'), ('system', 'System Alert'), ('factsheet_error', 'Factsheet Error'), ('risk_alert', 'Risk Metric Alert'), ('aum_change', 'AUM Change'), ('expense_ratio_change', 'Expense Ratio Change'), ('rating_change', 'Rating Change')], max_length=50),
        ),
        migrations.CreateModel(
            name='AlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_nav_changes', models.BooleanField(default=True, help_text='NAV movements > 5%')),
                ('email_holdings_changes', models.BooleanField(default=True, help_text='New/exited holdings')),
                ('email_sector_changes', models.BooleanField(default=False, help_text='Sector allocation changes')),
                ('email_risk_alerts', models.BooleanField(default=True, help_text='Risk metric warnings')),
                ('email_metadata_changes', models.BooleanField(default=False, help_text='Expense ratio, AUM, rating changes')),
                ('app_nav_changes', models.BooleanField(default=True)),
                ('app_holdings_changes', models.BooleanField(default=True)),
                ('app_sector_changes', models.BooleanField(default=True)),
                ('app_risk_alerts', models.BooleanField(default=True)),
                ('app_metadata_changes', models.BooleanField(default=True)),
                ('nav_threshold', models.DecimalField(decimal_places=2, default=5.0, help_text='Percentage', max_digits=5)),
                ('weight_change_threshold', models.DecimalField(decimal_places=2, default=2.0, help_text='Percentage', max_digits=5)),
                ('sector_change_threshold', models.DecimalField(decimal_places=2, default=5.0, help_text='Percentage', max_digits=5)),
                ('daily_digest_enabled', models.BooleanField(default=False)),
                ('digest_time', models.TimeField(default='09:00', help_text='Time for daily digest email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Preference',
                'verbose_name_plural': 'Alert Preferences',
            },
        ),
    ]
