# Generated by Django 6.0.3 on 2026-04-01 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Portfolio', max_length=200)),
                ('kite_access_token', models.CharField(blank=True, max_length=500)),
                ('kite_connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to='funds.mutualfund')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'fund')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.DecimalField(decimal_places=4, max_digits=16)),
                ('avg_nav', models.DecimalField(decimal_places=4, max_digits=14)),
                ('purchase_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='portfolio.portfoliofund')),
            ],
            options={
                'ordering': ['purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='XIRRCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xirr_value', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xirr_cache', to='portfolio.portfolio')),
                ('portfolio_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xirr_cache', to='portfolio.portfoliofund')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio_fund'], name='portfolio_x_portfol_88396a_idx'), models.Index(fields=['portfolio'], name='portfolio_x_portfol_aa7be3_idx')],
            },
        ),
    ]
