# Generated by Django 4.2.29 on 2026-04-02 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_mutualfund_aum_mutualfund_crisil_rating_and_more'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebalanceSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_equity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_debt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_gold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_equity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_debt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_gold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebalance_suggestions', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RebalanceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('units', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('reason', models.CharField(max_length=200)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.mutualfund')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='portfolio.rebalancesuggestion')),
            ],
            options={
                'ordering': ['action', '-amount'],
            },
        ),
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_percentage', models.DecimalField(decimal_places=2, default=60, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('debt_percentage', models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gold_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('large_cap_percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mid_cap_percentage', models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('small_cap_percentage', models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rebalance_threshold', models.DecimalField(decimal_places=2, default=5, help_text='Trigger rebalancing when allocation deviates by this percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocation', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Asset Allocation',
                'verbose_name_plural': 'Asset Allocations',
            },
        ),
    ]
