# Generated by Django 4.2.29 on 2026-04-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_mutualfund_aum_mutualfund_crisil_rating_and_more'),
        ('portfolio', '0002_rebalancesuggestion_rebalanceaction_assetallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebalanceaction',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funds.mutualfund'),
        ),
    ]
