# Generated by Django 4.2.29 on 2026-04-10 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_change_is_active_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0004_kitecredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='CASImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='PENDING', max_length=20)),
                ('investor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('investor_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('cas_type', models.CharField(blank=True, max_length=20, null=True)),
                ('statement_period_from', models.DateField(blank=True, null=True)),
                ('statement_period_to', models.DateField(blank=True, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('funds_processed', models.IntegerField(default=0)),
                ('transactions_processed', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('parser_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaselot',
            name='cas_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaselot',
            name='folio_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaselot',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchaselot',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('KITE', 'Zerodha Kite'), ('CAS', 'CAS Parser')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaselot',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('REDEMPTION', 'Redemption'), ('SWITCH_IN', 'Switch In'), ('SWITCH_OUT', 'Switch Out'), ('DIVIDEND_REINVEST', 'Dividend Reinvest')], default='PURCHASE', max_length=20),
        ),
        migrations.CreateModel(
            name='CASImportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_sync_enabled', models.BooleanField(default=False)),
                ('duplicate_handling', models.CharField(choices=[('SKIP', 'Skip Duplicates'), ('UPDATE', 'Update Existing'), ('MERGE', 'Merge with Existing')], default='SKIP', max_length=20)),
                ('default_notes', models.CharField(blank=True, max_length=300)),
                ('auto_categorize_switches', models.BooleanField(default=True)),
                ('data_source_priority', models.CharField(choices=[('CAS_FIRST', 'CAS Data First'), ('KITE_FIRST', 'Kite Data First'), ('MOST_RECENT', 'Most Recent Data')], default='CAS_FIRST', max_length=20)),
                ('retain_pan_data', models.BooleanField(default=False)),
                ('retain_contact_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cas_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CASTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('REDEMPTION', 'Redemption'), ('SWITCH_IN', 'Switch In'), ('SWITCH_OUT', 'Switch Out'), ('DIVIDEND_PAYOUT', 'Dividend Payout'), ('DIVIDEND_REINVEST', 'Dividend Reinvest')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('units', models.DecimalField(decimal_places=4, max_digits=16)),
                ('nav', models.DecimalField(decimal_places=4, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('folio_number', models.CharField(blank=True, max_length=50, null=True)),
                ('balance_units', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cas_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.casimport')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas_transactions', to='funds.mutualfund')),
                ('portfolio_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cas_transactions', to='portfolio.portfoliofund')),
                ('purchase_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cas_transaction', to='portfolio.purchaselot')),
            ],
            options={
                'ordering': ['transaction_date'],
                'indexes': [models.Index(fields=['cas_import', 'transaction_date'], name='portfolio_c_cas_imp_56486a_idx'), models.Index(fields=['fund', 'transaction_date'], name='portfolio_c_fund_id_aa4e91_idx'), models.Index(fields=['transaction_type'], name='portfolio_c_transac_b52d94_idx')],
                'unique_together': {('cas_import', 'fund', 'transaction_date', 'transaction_type', 'units', 'nav')},
            },
        ),
        migrations.AddIndex(
            model_name='casimport',
            index=models.Index(fields=['user', 'status'], name='portfolio_c_user_id_ff0610_idx'),
        ),
        migrations.AddIndex(
            model_name='casimport',
            index=models.Index(fields=['created_at'], name='portfolio_c_created_edd585_idx'),
        ),
    ]
