# Generated by Django 4.2.29 on 2026-04-10 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_add_holding_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='casimport',
            name='skipped_transactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='large_cap_percentage',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='mid_cap_percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
