# Generated by Django 4.2.29 on 2026-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_update_default_market_cap_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='casimport',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
