# Generated by Django 4.2.29 on 2026-04-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_add_file_hash_to_casimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casimport',
            name='statement_period_from',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='casimport',
            name='statement_period_to',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
