# Generated by Django 4.2.29 on 2026-04-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_add_indexes_to_statement_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CASImportSettings',
        ),
    ]
