# Generated by Django 4.2.29 on 2026-04-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_remove_cas_import_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casimport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success'), ('DUPLICATE', 'Duplicate')], default='PENDING', max_length=20),
        ),
    ]
