# Generated by Django 4.2.29 on 2026-04-10 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_add_duplicate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetallocation',
            name='debt_percentage',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='equity_percentage',
            field=models.DecimalField(decimal_places=2, default=75, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
