# Generated by Django 4.2.29 on 2026-04-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_update_default_allocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KiteCredentials',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='kite_access_token',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='kite_connected_at',
        ),
        migrations.AlterField(
            model_name='purchaselot',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('CAS', 'CAS Parser')], default='MANUAL', max_length=10),
        ),
    ]
