# Generated by Django 4.2.29 on 2026-04-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_delete_kitecredentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselot',
            name='units',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
    ]
