# Generated by Django 6.0.3 on 2026-04-01 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('fund_manager', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('objective', models.TextField(blank=True)),
                ('aum', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('fetch_error', models.TextField(blank=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factsheets', to='funds.mutualfund')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('fund', 'month')},
            },
        ),
        migrations.CreateModel(
            name='FactsheetFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('funds_processed', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.mutualfund')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FactsheetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=300)),
                ('isin', models.CharField(blank=True, max_length=20)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=6)),
                ('sector', models.CharField(blank=True, max_length=200)),
                ('factsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='factsheets.factsheet')),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='SectorAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=6)),
                ('factsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='factsheets.factsheet')),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='FactsheetDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_holdings', models.JSONField(default=list)),
                ('exited_holdings', models.JSONField(default=list)),
                ('weight_changes', models.JSONField(default=list)),
                ('sector_changes', models.JSONField(default=list)),
                ('manager_changed', models.BooleanField(default=False)),
                ('category_changed', models.BooleanField(default=False)),
                ('objective_changed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_as_current', to='factsheets.factsheet')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs', to='funds.mutualfund')),
                ('previous_month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diffs_as_previous', to='factsheets.factsheet')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('fund', 'current_month')},
            },
        ),
    ]
